// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMCPN2Q5egtU0nZrdoZRus2wpS_Z7gnwI',
    appId: '1:238263278588:web:d989f429257175d21ab079',
    messagingSenderId: '238263278588',
    projectId: 'adityachat-edbb4',
    authDomain: 'adityachat-edbb4.firebaseapp.com',
    storageBucket: 'adityachat-edbb4.firebasestorage.app',
    measurementId: 'G-698TR31WKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUsNrE5Vj-Ty4xr_aaAU7gDri-TiyxcEU',
    appId: '1:238263278588:android:f91dadcc5ba0ecd91ab079',
    messagingSenderId: '238263278588',
    projectId: 'adityachat-edbb4',
    storageBucket: 'adityachat-edbb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB3nUvLVfHgPHR9uuzOaBtAVPRZd5zMQk',
    appId: '1:238263278588:ios:ed10fabfb1029ce91ab079',
    messagingSenderId: '238263278588',
    projectId: 'adityachat-edbb4',
    storageBucket: 'adityachat-edbb4.firebasestorage.app',
    iosBundleId: 'com.example.adityaChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB3nUvLVfHgPHR9uuzOaBtAVPRZd5zMQk',
    appId: '1:238263278588:ios:ed10fabfb1029ce91ab079',
    messagingSenderId: '238263278588',
    projectId: 'adityachat-edbb4',
    storageBucket: 'adityachat-edbb4.firebasestorage.app',
    iosBundleId: 'com.example.adityaChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMCPN2Q5egtU0nZrdoZRus2wpS_Z7gnwI',
    appId: '1:238263278588:web:c1840071a2ba491b1ab079',
    messagingSenderId: '238263278588',
    projectId: 'adityachat-edbb4',
    authDomain: 'adityachat-edbb4.firebaseapp.com',
    storageBucket: 'adityachat-edbb4.firebasestorage.app',
    measurementId: 'G-FKRZG8Z67Z',
  );
}
